# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileset',
            name='datafile',
            field=models.FileField(upload_to=b''),
        ),
    ]
