# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0002_auto_20170206_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileset',
            name='datafile',
            field=models.TextField(),
        ),
    ]
